### ISSUE TITLE
Summarize Errors - Documentation

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#236]
Hi,

I am creating several invoices in a batch. How do I activate and use the summarize errors feature?

https://community.xero.com/developer/discussion/8991347

Here is my code:

`
try
                {
                    List<Invoice> invoices = m_Api.Create(m_Invoices).ToList();

                    m_SyncedInvoices.AddRange(invoices);

                    foreach (Invoice inv in invoices)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", inv.Number, inv.Contact.Name, inv.Date.Value)));
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        if (error.Message == "Invoice # must be unique.")
                            continue;

                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }`

**Comment by MJMortimer** [comment]
Hey @jmawebtech.

Based on the example that you've given you can do
`m_Api.SummarizeErrors(false);`
before the call to the Create method

**Comment by jmawebtech** [comment]
Hi,

Thanks for the code.

I upgraded to the latest edition of your code. I am using the partner MVC authenticator. Did I connect it incorrectly? In my XeroApiHelper class, I believe I hooked it up correctly:

// Partner Application Settings
            var partnerConsumer = new Consumer(partnerConsumerKey, partnerConsumerSecret);

            var partnerAuthenticator = new PartnerMvcAuthenticator(baseApiUrl, baseApiUrl, callbackUrl,
                    memoryStore, signingCertificatePath,
                    partnerConsumer, requestTokenStore, clientCertificatePassword);

            var partnerApplicationSettings = new ApplicationSettings
            {
                BaseApiUrl = baseApiUrl,
                Consumer = partnerConsumer,
                Authenticator = partnerAuthenticator
            };

            // Pick one
            // Choose what sort of application is appropriate. Comment out the above code (Partner Application Settings/Public Application Settings) that are not used.

            //_applicationSettings = publicApplicationSettings;
            _applicationSettings = partnerApplicationSettings;

When I try to search accounts, I get this error:

m_Api.Accounts.Find().ToList()

![auth](https://cloud.githubusercontent.com/assets/1679993/22047335/65fd8db4-dcf4-11e6-9f6e-2c93a5d1ac31.png)

Not Supported Exception:

at Xero.Api.Example.Applications.Public.PublicMvcAuthenticator.AuthorizeUser(IToken token) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api.Example.Applications\Public\PublicMvcAuthenticator.cs:line 22
   at Xero.Api.Example.Applications.TokenStoreAuthenticator.GetToken(IConsumer consumer) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api.Example.Applications\TokenStoreAuthenticator.cs:line 88
   at Xero.Api.Example.Applications.TokenStoreAuthenticator.GetToken(IConsumer consumer, IUser user) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api.Example.Applications\TokenStoreAuthenticator.cs:line 51
   at Xero.Api.Example.Applications.TokenStoreAuthenticator.GetSignature(IConsumer consumer, IUser user, Uri uri, String verb, IConsumer consumer1) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api.Example.Applications\TokenStoreAuthenticator.cs:line 39
   at Xero.Api.Infrastructure.Http.HttpClient.CreateRequest(String endPoint, String method, String accept, String query) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\HttpClient.cs:line 184
   at Xero.Api.Infrastructure.Http.HttpClient.Get(String endpoint, String query) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\HttpClient.cs:line 106
   at Xero.Api.Infrastructure.Http.XeroHttpClient.Get[TResult,TResponse](String endPoint) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\XeroHttpClient.cs:line 55
   at Xero.Api.Common.XeroReadEndpoint`3.Get(String endpoint, String child) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Common\XeroReadEndpoint.cs:line 175
   at Xero.Api.Common.XeroReadEndpoint`3.Find() in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Common\XeroReadEndpoint.cs:line 74
   at ConnexForXero.XeroApiProvider.XeroProvider.SearchAccounts(String name) in C:\Users\joe_a84\Source\Workspaces\ConnexForXero\Source\ConnexForXero.XeroApiProvider\XeroProvider.cs:line 864
   at ConnexForXero.XeroApiProvider.XeroProvider..ctor(String connectionString, String userName, TaskNameEnum taskName, JMAUser jmaUser, IJMALogProvider logProvider, JMASettings settings) in C:\Users\joe_a84\Source\Workspaces\ConnexForXero\Source\ConnexForXero.XeroApiProvider\XeroProvider.cs:line 37
   at ConnexForXero.ConsoleClient.Program.Main(String[] args) in C:\Users\joe_a84\Source\Workspaces\ConnexForXero\Test\ConnexForXero.ConsoleClient\Program.cs:line 74
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MJMortimer** [comment]
Hey @jmawebtech, did you end up resolving the last error posted above, and if so is there anything you can add to this issue that could help others that may end up with the same issue?

**Comment by jmawebtech** [comment]
Hi,


Yes, I resolved it. I had to upgrade to your latest code. May I update your software documentation? Here is my solution:


            if (m_Invoices.Count() > 0)
            {
                m_Api.Invoices.SummarizeErrors(false);
                List<Invoice> invoices = m_Api.Create(m_Invoices).ToList();

                if (invoices.Any()) // check for invoices
                {
                    foreach (Invoice inv in invoices)
                    {
                        //Check For any Errors
                        if (inv.Errors != null)
                        {
                            foreach (ValidationError error in inv.Errors)
                            {
                                if (error.Message == "Invoice # must be unique.")
                                    continue;

                                m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", inv.Number, error.Message), inv.Number));
                            }
                        }
                        else
                        {
                            m_SyncedInvoices.AddRange(invoices);
                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", inv.Number, inv.Contact.Name, inv.Date.Value), inv.Number));
                        }
                    }
                }
            }





Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com

________________________________

**Comment by jmawebtech** [comment]
Hi,

Yes, I resolved it.

My solution uses the SqlTokenStore and I made a table with these values:

UserId, OrganisationId, ConsumerKey, ConsumerSecret, TokenKey, TokenSecret, ExpiresAt, Session, SessionExpiresAt

There was no record matching the UserId. If your integration finds no user, it throws that error.
