### ISSUE TITLE
SerializationException from Contacts endpoint

### ISSUE THREAD

**Issue by rayperkins** [XeroAPI/Xero-Net#334]
I am catching an occasional SerializationException when querying the Contacts endpoint. This happens a few times a day, but works of the time. The application logs the exception and then 5 minutes later repeats the query without issue. I have been unable to replicate the exception when performing the same queries while debugging the application.

It seems that the Xero API is infrequently not returning valid JSON.
The SDK version I am using is: 2.2.2, Xero.Api.SDK.Minimal

Exception Stacktrace:
```
[07/16/2018 18:45:11 > e6b2f3: INFO] 2018-07-16 18:45:08,764 [1] ERROR Console [(null)] - System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'ApiException', got string starting with: <HTML><HEAD>
[07/16/2018 18:45:11 > e6b2f3: INFO] <TITLE>Bad Request</TITLE>
[07/16/2018 18:45:11 > e6b2f3: INFO] </HEAD><BO
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(Type type, String strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.Common.DeserializeType`1.<>c__DisplayClass1_0.<GetParseMethod>b__1(String value)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.Json.JsonReader`1.Parse(String value)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Serialization.DefaultMapper.Xero.Api.Infrastructure.Interfaces.IJsonObjectMapper.From[T](String result)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrors(Response response)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.Http.XeroHttpClient.Read[TResult,TResponse](Response response)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Infrastructure.Http.XeroHttpClient.Get[TResult,TResponse](String endPoint)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Common.XeroReadEndpoint`3.Get(String endpoint, String child)
[07/16/2018 18:45:11 > e6b2f3: INFO]    at Xero.Api.Common.XeroReadEndpoint`3.Find()
```

**Comment by MatthewSteeples** [comment]
We were seeing these too. We suspect it was down to an unpublished outage (server was returning HTML instead of JSON)

**Comment by rayperkins** [comment]
After collecting more logging I suspect there is an issue. We have the occasional (every few days) Bad Request returned from the Xero API. We have seen this when Refresh Tokens and querying contacts.

`<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;<ref code here>
</BODY>
</HTML>
`

The .Net SDK version used is now v2.2.8, Xero.Api.SDK.Minimal.
Based on that our client code does not change and works most of the time, I am wondering if there is an occasional outage at Xero's end.

@MatthewSteeples, have you seen any more similar issues?

**Comment by MatthewSteeples** [comment]
@rayperkins We raised a support request about the Refresh Tokens endpoint doing things like this a while back (CX0006715273 if you want to reference it if you end up raising a case). We found in those circumstances that we'd effectively "lost" our auth token because we never received the new one, but Xero issuing the new one invalidated the old one.

In general though, we see this kind of behaviour on all endpoints. We've mostly just build exception handlers around the calls that wait for a period and then retry the request (without condition for a "read", and trying to check if it's already been done for a "write")

**Comment by MJMortimer** [comment]
Hi @rayperkins, is this still an issue for you?

**Comment by rayperkins** [comment]
@MJMortimer, we still see regular Bad Request responses with an HTML body instead of JSON. 
This causes a SerializationException from ServiceStack within the Xero API client.

**Comment by MJMortimer** [comment]
Hey @rayperkins, this sounds like an issue with the underlying API itself. Have you raised a support ticket with the team for a deeper investigation yet? If not, then this is probably your best avenue forward.

As MatthewSteeples has mentioned, the best thing to do in this case is handle any unexpected exceptions in your code, and retry any failed operations.

**Comment by kiennk1995** [comment]
Hi @MJMortimer 
Today I got this issue even though my code does not change and works most of the time too.

Message: Type definitions should start with a '{', expecting serialized type 'ApiException', got string starting with: oauth_problem=signature_method_rejected&oauth_prob
   at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(Type type, String strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
   at Xero.Api.Infrastructure.ThirdParty.ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
   at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrors(Response response)
   at Xero.Api.Infrastructure.Http.XeroHttpClient.Read[TResult,TResponse](Response response)
   at Xero.Api.Common.XeroReadEndpoint`3.Get(String endpoint, String child)

**Comment by SidneyAllen** [comment]
We are archiving this repository in conjunction with our deprecation of OAuth 1.0a. If you wish use Xero-Net going forward you have the option of forking the Xero-Net repository. We recommend moving to Xero-NetStandard SDK for OAuth 2.0 as it will be supported and maintained going forward. https://github.com/XeroAPI/Xero-NetStandard

If you need more time to complete your migration to OAuth 2, please contact api@xero.com for assistance.
