### ISSUE TITLE
When 504 happened, SDK can't throw exception correctlly

### ISSUE THREAD

**Issue by sevendark** [XeroAPI/Xero-Net#410]
I got this exception, but actually it's 504 error.

```
2019-11-08 02:00:02,133 - ERROR c.x.a.e.XeroExceptionHandler [DefaultDispatcher-worker-3] - com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
	at com.xero.api.exception.XeroExceptionHandler.handleBadRequest(XeroExceptionHandler.java:114)
	at com.xero.api.client.AccountingApi.createInvoice(AccountingApi.java:1181)
```

```
java.lang.NullPointerException: null
	at com.xero.api.client.AccountingApi.createInvoice(AccountingApi.java:1181)
```

**Comment by sevendark** [comment]
Wrong place
